### ISSUE TITLE
Offer to collaborate

### ISSUE THREAD

**Issue by mattsaxon** [frenck/python-sonoffdiy#1]
Hi @frenck,

I saw a set of issues you've created on the ITead Sonoff DIY repo, in particular this one https://github.com/itead/Sonoff_Devices_DIY_Tools/issues/5 got my attention as I've been looking at fallback too.

I've been working on a Sonoff module for sometime and the code is here https://github.com/mattsaxon/pysonofflan/

There is also a HA custom component here https://github.com/mattsaxon/sonoff-lan-mode-homeassistant/

I've had the Sonoff DIY working, but my main reason for doing this was to use non DIY devices (as not all device types have a DIY mode and I have a large number of the legacy ones too). I didn't want to use Tasmota for various reasons.

I have around 20 devices working in my house for around 6 months now and the code is pretty reliable.

Given that I've seen you are a key member of the HA community, I suspect you are going to be integrating it into HA and I'd be keen to assist you with what I've learnt, in particular, I think that supporting legacy (non DIY devices) is fairly easy to do and I'd like to see them supported by whatever you are thinking of delivering.

**Comment by frenck** [comment]
> I think that supporting legacy (non DIY devices) is fairly easy to do

Not planning on doing that, since that interface is not meant for that. That should go into separate packages and integrations.

Sonoff DIY mode is meant to be as a clean alternative to that, let's keep it that way.

**Comment by mattsaxon** [comment]
You are right if you are considering documented interfaces, but the standard devices implement virtually the same interface but with encryption turned on. So supporting encryption is pretty much all that is required.

This was publicly documented previously, though more recent documents have dropped the information. 

What are you plans for this component, do you intend it to be a fully integrated HA component eventually?

**Comment by frenck** [comment]
> You are right if you are considering documented interfaces, but the standard devices implement virtually the same interface but with encryption turned on. So supporting encryption is pretty much all that is required.

There is more involved here. For example, not relying solely on mDNS broadcasting, but falling back and a lot more small differences (for example, the sequence doesn't matter).

This is not a component but a package. I'm in contact with the devs of Sonoff for quite a while now and awaiting some more changes in order to make a nice implementation in HA eventually. However, with the current status of the DIY firmware, I would not recommend anybody using it.

**Comment by mattsaxon** [comment]
Agreed. mDNS is quite an issue here. I’m not sure if you are aware, but there older firmware used websockets.

Devices in. On DIY mode don’t implement the /info endpoint, so at the moment, I can see no fallback possibility.

In terms of the sequence, there is another field, ‘Seq’ in the responses too, which could be useful, but not ideal.

Glad you are pursuing this!
